apiVersion: v1
kind: ServiceAccount
metadata:
  name: nmap-sa
  namespace: test-project
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: nmap-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: nmap-sa
  namespace: test-project
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: ocpscan-clusterrole
  apiGroup: ""
---
apiVersion: v1
kind: Pod
metadata:
  name: nmap-mounted
  labels:
    name: nmap-mounted
    context: nmap-mounted-tool
spec:
  serviceAccountName: nmap-sa
  containers:
    -
      name: nmap-mounted
      image: raesene/alpine-containertools
---
apiVersion: v1
kind: Pod
metadata:
  name: nmap
  labels:
    name: nmap
    context: nmap-tool
spec:
  serviceAccountName: nmap-sa
  automountServiceAccountToken: false
  containers:
    -
      name: nmap
      image: raesene/alpine-containertools
