apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: vulrep
  name: vulrep
spec:
  replicas: 1
  selector:
    app: vulrep
  template:
    metadata:
      labels:
        app: vulrep
    spec:
      containers:
      - image: danmx/docker-owasp-webgoat
        name: vulrep
        ports:
        - containerPort: 8080
