apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    name: mongo
    context: docker-chat
spec:
  containers:
    -
      name: mongo
      image: mongo:latest
      ports:
        -
          containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
    context: docker-chat
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo
    context: docker-chat
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: demochat
  labels:
    name: demochat
    context: docker-chat
spec:
  replicas: 1
  selector:
    name: demochat
    deploymentconfig: demochat
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        name: demochat
        deploymentconfig: demochat
        context: docker-chat
    spec:
      containers:
      - name: demochat-dc-pod
        image: prasenforu/demochat:1.0
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: demochat
  labels:
    name: demochat
    context: docker-chat
spec:
  ports:
  - name: 5000-tcp
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    name: demochat
    context: docker-chat
    deploymentconfig: demochat
---
apiVersion: v1
kind: Route
metadata:
  labels:
  context: docker-chat
  name: demochat
spec:
  host: demochat.cloudapps.cloud-cafe.in
  port:
    targetPort: 5000-tcp
  to:
    kind: Service
    name: demochat
