apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: dockstress
  name: dockstress
spec:
  replicas: 1
  selector:
    app: dockstress
    deploymentconfig: dockstress
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: dockstress
        deploymentconfig: dockstress
    spec:
      containers:
      - image: prasenforu/dockstress
        imagePullPolicy: IfNotPresent
        name: dockstress
      restartPolicy: Always
      
