apiVersion: v1
kind: Route
metadata:
  labels:
    app: memoryeater
  name: memoryeater-route
spec:
  host: memoryeater.cloudapps.cloud-cafe.in
  port:
    targetPort: 80-tcp
  to:
    kind: Service
    name: memoryeater-service

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: memoryeater
  name: memoryeater-service
spec:
  clusterIP: 172.30.200.90
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: memoryeater
    deploymentconfig: memoryeater

---

apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: memoryeater
  name: memoryeater
spec:
  replicas: 1
  selector:
    app: memoryeater
    deploymentconfig: memoryeater
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: memoryeater
        deploymentconfig: memoryeater
    spec:
      containers:
      - image: prasenforu/memoryeater
        name: memoryeater-image
        ports:
        - name: memoryeater
          containerPort: 80
