apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    name: mongo
    context: docker-pkar
spec:
  containers:
    -
      name: mongo
      image: mongo:3.4.0
      ports:
        -
          containerPort: 27017
----
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
    context: docker-pkar
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo
    context: docker-pkar
----
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: myemp
  labels:
    name: myemp
    context: docker-pkar
spec:
  replicas: 1
  selector:
    name: myemp
    deploymentconfig: myemp
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        name: myemp
        deploymentconfig: myemp
        context: docker-pkar
    spec:
      containers:
      - name: myemp-dc-pod
        image: prasenforu/employee
        ports:
        - containerPort: 8888
----
apiVersion: v1
kind: Service
metadata:
  name: myemp
  labels:
    name: myemp
    context: docker-pkar
spec:
  clusterIP: 172.30.200.91
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    name: myemp
    context: docker-pkar
    deploymentconfig: myemp
---
apiVersion: v1
kind: Route
metadata:
  labels:
  context: docker-pkar
  name: myemp
spec:
  host: sampleapp.cloudapps.cloud-cafe.in
  port:
    targetPort: 80-tcp
  to:
    kind: Service
    name: myemp
