{
 "title": "OCP Project Monitoring",
 "description": "Monitors Openshift cluster using prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [ "Openshift" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   },
   { "name": "Project", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Project memory usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_max_usage_bytes{pod_name!=\"\",namespace=~\"^$Project$\"} ) / (sum (node_memory_MemTotal_bytes{kubernetes_io_hostname=~\"^$Node$\"})) * 100"
    }
   ]
  },
  {
   "title": "Project CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (sum by (pod_name)( rate(container_cpu_usage_seconds_total{namespace=~\"^$Project$\"}[2m] ) ))/sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})*100"
    }
   ]
  },
  {
   "title": "Cluster Docker fs usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=\"docker--vg-docker--pool\",id=\"/\",instance!=\"\"}) / sum (container_fs_limit_bytes{device=\"docker--vg-docker--pool\",id=\"/\",instance!=\"\"}) * 100"
    }
   ]
  },
  {
   "title": "Pods Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "sort_desc (sum (container_memory_max_usage_bytes{image!=\"\",pod_name!=\"\",namespace=~\"^$Project$\",iinstance=~\"^$Node$\"}) by (pod_name,instance))",
     "legendFormat": "{{ pod_name }} "
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_max_usage_bytes{namespace=~\"^$Project$\"})"
    }
   ]
  },
  {
   "title": "Total Cluster",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (sum by (pod_name)( rate(container_cpu_usage_seconds_total{namespace=~\"^$Project$\"}[2m] ) ))"
    }
   ]
  },
  {
   "title": "Total Cluster",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=\"docker--vg-docker--pool\",id=\"/\",instance!=\"\"})"
    }
   ]
  },
  {
   "title": "Total Cluster",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=\"docker--vg-docker--pool\",id=\"/\",instance!=\"\"})"
    },
    {
     "expr": "sum(node_filesystem_avail_bytes {device=\"/dev/mapper/docker_vg-docker--root--lv\", mountpoint=\"/etc/hostname\" , region=\"app\" })"
    }
   ]
  },
  {
   "title": "Mem Limit Utilization",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_resourcequota{namespace=~\"^$Project$\",resource=\"limits.memory\",type=\"used\"}) / sum (kube_resourcequota{namespace=~\"^$Project$\",resource=\"limits.memory\",type=\"hard\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU Limit Utilization",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_resourcequota{namespace=~\"^$Project$\",resource=\"limits.cpu\",type=\"used\"}) / sum (kube_resourcequota{namespace=~\"^$Project$\",resource=\"limits.cpu\",type=\"hard\"}) * 100"
    }
   ]
  },
  {
   "title": "Number of PODs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"pods\",type=\"used\",namespace=~\"^$Project$\"}) / sum(kube_resourcequota{resource=\"pods\",type=\"hard\",namespace=~\"^$Project$\"}) * 100"
    }
   ]
  },
  {
   "title": "Pods CPU usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Project$\",instance=~\"^$Node$\"}[2m])) by (pod_name,instance)",
     "legendFormat": "{{ pod_name }} "
    }
   ]
  },
  {
   "title": "M-Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 8 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_resourcequota{namespace=~\"^$Project$\",resource=\"limits.memory\",type=\"used\"})"
    }
   ]
  },
  {
   "title": "M-Hard",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 8 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_resourcequota{namespace=~\"^$Project$\",resource=\"limits.memory\",type=\"hard\"})"
    }
   ]
  },
  {
   "title": "C-used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_resourcequota{namespace=~\"^$Project$\",resource=\"limits.cpu\",type=\"used\"})"
    }
   ]
  },
  {
   "title": "C-Hard",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_resourcequota{namespace=~\"^$Project$\",resource=\"limits.cpu\",type=\"hard\"})"
    }
   ]
  },
  {
   "title": "P-Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_resourcequota{resource=\"pods\",type=\"used\",namespace=~\"^$Project$\"}"
    }
   ]
  },
  {
   "title": "P-Hard",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_resourcequota{resource=\"pods\",type=\"hard\",namespace=~\"^$Project$\"}"
    }
   ]
  },
  {
   "title": "PVC utilization",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_resourcequota {resource=\"persistentvolumeclaims\",type=\"used\",namespace=~\"^$Project$\"}) / sum (kube_resourcequota {resource=\"persistentvolumeclaims\",type=\"hard\",namespace=~\"^$Project$\"}) *100"
    }
   ]
  },
  {
   "title": "PV Utilization",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.storage\",type=\"used\",namespace=~\"^$Project$\"}) / sum(kube_resourcequota{resource=\"requests.storage\",type=\"hard\",namespace=~\"^$Project$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster Persistent Storage usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (heketi_device_used{job=\"gluster-server\"}) / sum (heketi_device_size{job=\"gluster-server\"}) * 100"
    }
   ]
  },
  {
   "title": "PV resource Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_resource_requests_storage_bytes {namespace=~\"^$Project$\"}",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "PVC (Used)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_resourcequota {resource=\"persistentvolumeclaims\",type=\"used\",namespace=~\"^$Project$\"}"
    }
   ]
  },
  {
   "title": "PVC (Hard)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_resourcequota {resource=\"persistentvolumeclaims\",type=\"hard\",namespace=~\"^$Project$\"}"
    }
   ]
  },
  {
   "title": "PV (Used)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 13 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_resourcequota {resource=\"requests.storage\",type=\"used\",namespace=~\"^$Project$\"}"
    }
   ]
  },
  {
   "title": "PV (Hard)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 13 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_resourcequota {resource=\"requests.storage\",type=\"hard\",namespace=~\"^$Project$\"}"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 13 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(round(heketi_device_used{job=\"gluster-server\"} / 1.047e+06))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 13 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(round(heketi_device_size{job=\"gluster-server\"} / 1.047e+06))"
    }
   ]
  },
  {
   "title": "Route Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (route) (haproxy_backend_connections_total{backend=~\"https\",namespace=~\"^$Project$\",job=\"openshift-router\"})",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "High Web Error (5XX) Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (route,instance) (rate (haproxy_server_http_responses_total{code=~\"5xx\",namespace=~\"^$Project$\",route!=\"\"}[5m])) > 0",
     "legendFormat": "{{ route }} ( {{ instance }} )"
    }
   ]
  },
  {
   "title": "Backend Error Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (route,instance) (rate (haproxy_server_response_errors_total{namespace=~\"^$Project$\",route!=\"\"}[5m])) > 0",
     "legendFormat": "{{ route }} ( {{ instance }} )"
    }
   ]
  },
  {
   "title": "Pods network I/O",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Project$\",kubernetes_io_hostname=~\"^$Node$\"}[2m])) by (pod_name)",
     "legendFormat": "-> {{ pod_name }}"
    }
   ]
  }
 ]
}