apiVersion: v1
kind: Config
clusters:
- name: falco
  cluster:
    server: http://falco-service.security.svc.cluster.local:8765/k8s_audit
contexts:
- context:
    cluster: falco
    user: ""
  name: default-context
current-context: default-context
preferences: {}
users: []
