apiVersion: audit.k8s.io/v1beta1
kind: Policy
rules:
  - level: Metadata
    userGroups: ["system:authenticated:oauth"]
    verbs: ["create", "delete"]
    resources:
      - group: "project.openshift.io"
        resources: ["projectrequests", "projects"]
    omitStages:
      - RequestReceived
  - level: Metadata
    userGroups: [""]
    resources:
      - group: "rbac.authorization.k8s.io"
        resources: ["clusterroles", "clusterrolebindings"]
    omitStages:
      - RequestReceived
  - level: Metadata
    userGroups: [""]
    resources:
      - group: ""
        resources: ["secrets", "configmaps"]
    omitStages:
      - RequestReceived
  - level: Metadata
    nonResourceURLs:
      - /login* 
      - /oauth* 
    omitStages:
      - RequestReceived
