apiVersion: v1
kind: ServiceAccount
metadata:
  name: ocpscan-sa
  namespace: security
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ocpscan-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: ocpscan-sa
  namespace: security
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: ocpscan-clusterrole
  apiGroup: ""
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ocpscan-clusterrole
rules:
- apiGroups: ["*"]
  resources: ["roles", "clusterroles", "rolebindings", "clusterrolebindings", "pods", "secrets"]
  verbs: ["get", "list"]
- apiGroups: ["*"]
  resources: ["pod/exec"]
  verbs: ["create"]
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ocpscan
  name: ocpscan-service
spec:
  ports:
  - name: 9000-tcp
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: 9001-tcp
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: ocpscan
    deploymentconfig: ocpscan-dc
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: ocpscan
  name: ocpscan-dc
spec:
  replicas: 1
  selector:
    app: ocpscan
    deploymentconfig: ocpscan-dc
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: ocpscan
        deploymentconfig: ocpscan-dc
    spec:
      serviceAccount: ocpscan-sa
      serviceAccountName: ocpscan-sa
      containers:
      - image: xxxxxxxxxxx
        name: ocpscan
        ports:
        - name: ocpscan
          containerPort: 9000
        volumeMounts:
        - mountPath: /log
          name: ocpscanlog-path-volume-config
        - mountPath: /etc/webhook/hooks.json
          subPath: hooks.json
          name: ocpscan-hooks-volume-config
        - mountPath: /etc/webhook/scanner.sh
          subPath: scanner.sh
          name: ocpscan-scanscript-volume-config
        env:
        - name: KUBEHOST
          value: "masterb"
        - name: KUBEPORT
          value: "8443"
        - name: KUBEUSER
          value: "admin"
        - name: KUBEPASS
          value: "redhat"
        - name: KUBETOKEN
          value: "T O K E N"
        - name: SNURL
          value: ""
        - name: SNUSER
          value: ""
        - name: SNPASS
          value: ""
        - name: SNCALLID
          value: "containeradmin"
        - name: SNPRIORITY
          value: "1"
        - name: SNCATAGORY
          value: "Software"
        - name: SNASSINGRP
          value: "Container"
        - name: SNASSINTO
          value: ""
        - name: SNINCID
          value: "ServiceNow Incident ID"
      - image: yyyyyyyyyyy
        name: log2browser
        ports:
        - name: ocpscanlog
          containerPort: 9001
        args: ["/log/output.log"]
        volumeMounts:
        - mountPath: /log
          name: ocpscanlog-path-volume-config
      volumes:
      - name: ocpscanlog-path-volume-config
        emptyDir: {}
      - configMap:
          defaultMode: 420
          name: ocpscan-hooks-configmap
        name: ocpscan-hooks-volume-config
      - configMap:
          defaultMode: 493
          name: ocpscan-scanscript-configmap
        name: ocpscan-scanscript-volume-config
