apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-storage-demo
spec:
  hard:
    pods: "6"
    requests.cpu: "2"
    requests.memory: 4Gi
    requests.storage: "15Gi"
    limits.cpu: "3"
    limits.memory: "8Gi"
    persistentvolumeclaims: "5"
