apiVersion: v1
kind: DeploymentDeploymentConfig
metadata:
  name: app-b-allow3306
  namespace: test-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: app-b-allow3306
    spec:
      containers:
      - image: prasenforu/phpapp:5.0
        imagePullPolicy: Always
        name: app-b-allow3306
        ports:
        - containerPort: 80
        env:
        - name: EXTERNALIP
          value: "PUT EXTERNAL DB IP"
        - name: INTERNALIP
          value: "PUT INTERNAL DB IP"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: app-b-allow3306
  name: app-b-allow3306
  namespace: test-db
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: app-b-allow3306
---
apiVersion: v1
kind: Route
metadata:
  labels:
    k8s-app: app-b-allow3306
  name: app-b-allow3306
  namespace: test-db
spec:
  host: app-b-allow3306.test-db.cloudapps.cloud-cafe.in
  port:
    targetPort: 80
  to:
    kind: Service
    name: app-b-allow3306
