apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-graylog.conf
  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Merge_Log           On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        Labels              Off
        Annotations         Off
    # ${HOSTNAME} returns the host name.
    # But Fluentbit runs in a container. So, it is not meaningful.
    # Instead, copy the host name from the Kubernetes object.
    [FILTER]
        Name nest
        Match *
        Operation lift
        Nested_under kubernetes
    # Rename and add fields to be valid against the GELF format.
    # See http://docs.graylog.org/en/2.5/pages/gelf.html
    # Keep the "time" field, as it is not a timestamp.
    [FILTER]
        Name modify
        Match *
        Rename log short_message
        Rename stream _stream
        Rename @timestamp timestamp
        Rename pod_name _k8s_pod_name
        Rename namespace_name _k8s_namespace_name
        Rename pod_id _k8s_pod_id
        Rename labels _k8s_labels
        Rename container_name _k8s_container_name
        Rename docker_id _docker_id
        Add version 1.1
    # Remove useless fields
    [FILTER]
        Name record_modifier
        Match *
        Remove_key annotations
        Remove_key _k8s_labels
        Remove_key kubrnetes
        Remove_key kubernetes
  output-graylog.conf: |
    [OUTPUT]
        Name          gelf
        Match         *
        Host          GRAYLOG-SERVER
        Port          12201
        Mode          tcp
        Gelf_Short_Message_Key short_message
  parsers.conf: |
    [PARSER]
        Name   json
        Format json
        Time_Key time
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
        # Command      |  Decoder | Field | Optional Action
        # =============|==================|=================
        Decode_Field_As   escaped    log
    [PARSER]
        Name        syslog
        Format      regex
        Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key    time
        Time_Format %b %d %H:%M:%S
