kind: Service
apiVersion: v1
metadata:
  name: gluster-server
  labels:
    k8s-app: gluster-server
spec:
  externalName: 10.138.0.3
  type: ExternalName
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: gluster-server
  labels:
    k8s-app: gluster-server
subsets:
- addresses:
  - ip: 10.138.0.3
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gluster-server
  labels:
    k8s-app: gluster-server
spec:
  selector:
    matchLabels:
      k8s-app: gluster-server
  namespaceSelector: {}
  endpoints:
  - port: metrics
    interval: 10s
    honorLabels: true
    path: /metrics
