apiVersion: v1
kind: Config
clusters:
- name: ocpscan
  cluster:
    server: http://ocpscan-service.security.svc.cluster.local:9000/hooks/ocpscan-hook
contexts:
- context:
    cluster: ocpscan
    user: ""
  name: ocpscan-context
current-context: ocpscan-context
preferences: {}
users: []
