apiVersion: v1
kind: Service
metadata:
  labels:
    app: ocpscan
  name: ocpscan-service
spec:
  ports:
  - name: 9000-tcp
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: 9001-tcp
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: ocpscan
    deploymentconfig: ocpscan-dc
