kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ocpscan-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gluster-storage
