apiVersion: v1
kind: ServiceAccount
metadata:
  name: ocpscan-sa
  namespace: security
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ocpscan-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: ocpscan-sa
  namespace: security
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: ocpscan-clusterrole
  apiGroup: ""
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ocpscan-clusterrole
rules:
  - apiGroups:
    - "*"
    resources:
    - pods
    - namespaces
    - roles
    - clusterroles
    - rolebindings
    - clusterrolebindings
    - secrets
    verbs:
    - list
    - get
  - apiGroups:
    - "*"
    resources:
    - pods/exec
    verbs:
    - get
    - create
  - apiGroups:
    - "*"
    resources:
    - pods/exec
    verbs:
    - "*"
  - apiGroups:
    - extensions
    resources:
    - daemonsets
    - deployments
    - deployments/scale
    - replicasets
    - replicasets/scale
    - replicationcontrollers/scale
    verbs:
    - '*'
