scrape_configs:
  - job_name: system
    entry_parser: raw
    static_configs:
      - targets:
          - localhost
        labels:
          job: ocpscan-output
          host: ocpscanprom
          __path__: /log/output.log
