apiVersion: v1
kind: ServiceAccount
metadata:
  name: ocpscan-sa
  namespace: security
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ocpscan-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: ocpscan-sa
  namespace: security
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: ocpscan-clusterrole
  apiGroup: ""
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ocpscan-clusterrole
rules:
  - apiGroups:
    - "*"
    resources:
    - pods
    - namespaces
    - roles
    - clusterroles
    - rolebindings
    - clusterrolebindings
    - secrets
    verbs:
    - list
    - get
  - apiGroups:
    - "*"
    resources:
    - pods/exec
    verbs:
    - get
    - create
  - apiGroups:
    - "*"
    resources:
    - pods
    - replicationcontrollers
    - replicationcontrollers/scale
    verbs:
    - "*"
  - apiGroups:
    - extensions
    resources:
    - daemonsets
    - deployments
    - deployments/scale
    - replicasets
    - replicasets/scale
    - replicationcontrollers
    - replicationcontrollers/scale
    - statefulsets
    - statefulsets/scale
    verbs:
    - '*'
  - apiGroups: ["velero.io"]
    resources: ["backups", "backupstoragelocations", "downloadrequests", "podvolumebackups", "resticrepositories", "serverstatusrequests", "volumesnapshotlocations"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["velero.io"]
    resources: ["podvolumerestores", "restores"]
    verbs: ["create", "get", "watch", "list", "patch", "update"]    
