apiVersion: v1
kind: Pod
metadata:
  name: ocpwatch
spec:
  serviceAccount: ocpwatch
  serviceAccountName: ocpwatch
  containers:
  - image: coder95/kubewatch
    imagePullPolicy: Always
    name: ocpwatch
    volumeMounts:
    - name: config-volume
      mountPath: /root
  restartPolicy: Always
  volumes:
  - name: config-volume
    configMap:
      name: ocpwatch
